# This is a basic workflow to help you get started with Actions

name: CI

on:

  push:
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  first_build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Welcome Message
        run: echo "My first Github Action Job"

      - 

      # Runs a set of commands using the runners shell
      - name: List files on repo
        run: ls

      - name: Read File
        run: cat README.md
